### PR TITLE
Updated UI

### LINKED ISSUE #37: Create UI for Oracle
Add controls for interacting with the interface

### PR DESCRIPTION
**Pull request by mooncollin**
Closes #37 

Created zoom slider, floor changer, and statistic boxes on nodes. Nodes are primitive circle thingies right now. Paths are not yet created.

Movement can be done through keyboard or dragging on the screen.
Check out the small video in the zip attachment.

[2020-04-05 01-00-23.zip](https://github.com/dbrink1108/PKIIPS/files/4433028/2020-04-05.01-00-23.zip)

### CODE REVIEW

**Comment by mooncollin** [comment]
Might need to fix a little thing

**Review by dbrink1108 — APPROVED** [review]
Looks Good!

**Review by pgayee694 — CHANGES_REQUESTED** [review]
Align the floor buttons with the slider. Move them a bit closer together as well.

**Comment by pgayee694** [comment]
Write some docs

**Comment by mooncollin** [comment]
wrote some docs

**Review by pgayee694 — APPROVED** [review]

**Pull request merged**
