### PR TITLE
Initial Oracle commit

### LINKED ISSUE #32: initial oracle commit

### PR DESCRIPTION
**Pull request by mooncollin**
closes #32 

A very plain Unity scene to show what the look and feel of the application will be like. There isn't UI yet, just objects in the scene.

We have rooms (painted as blue), paths (painted as yellow), and exits (painted as red).

### CODE REVIEW

**Comment by mooncollin** [comment]
Capture

**Comment by pgayee694** [comment]
2d

**Review by pgayee694 — CHANGES_REQUESTED** [review]
we should be making a 2d map

**Comment by mooncollin** [comment]
Capture

**Review by pgayee694 — APPROVED** [review]
image

**Review by svnphlps — APPROVED** [review]

**Pull request merged**
